name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Default action: run something (prepares the Python environment)
      - name: Prepare Python ${{ matrix.python-version }}
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install wheel

      - name: Install package and build dependencies for Python ${{ matrix.python-version }}
        shell: bash -l {0}
        run: |
          pip install .
          pip install -r requirements.txt

      - name: Run all tests
        shell: bash -l {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          breton_cretenet_results
          pytest -sv --cov=breton_cretenet breton_cretenet/test.py

      - name: Build documentation
        if: ${{ matrix.python-version == '3.10' }}
        shell: bash -l {0}
        run: |
          sphinx-build doc doc/_build
          touch doc/_build/.nojekyll

      - name: Deploy documentation to GitHub Pages
        if: ${{ matrix.python-version == '3.10' && startsWith(github.ref, 'refs/tags') }}
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: doc/_build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
